D2IQ-72342: small improvements that are breaking changnes
dcos-labs/ui-kit pull request #569
Opened 2020-11-05 01:16 UTC by mperrotti

## Testing

Just confirm there were no regressions

## Trade-offs

## Dependencies

## Screenshots

## Checklist for PR creator

- [ ] If any new components were added, there are exported from `packages/index.ts`
- [ ] If this PR is associated with a JIRA, it is mentioned in commit message footer ("Closes …")
- [ ] If this PR contains breaking changes, is stated in commit message body ("BREAKING CHANGE: …")
- [x] Info for applicable sections above is provided

2020-11-07 00:06 UTC, natmegs approved these changes

2020-11-10 22:26 UTC, TattdCodeMonkey requested changes
mostly good, but found some console.logs that I'll remove.

2020-11-10 22:26 UTC, TattdCodeMonkey commented on packages/clicktocopybutton/components/ClickToCopy.tsx
> +    console.log("onClick is firing");
we should remove theses

2020-11-10 22:26 UTC, TattdCodeMonkey commented on packages/clicktocopybutton/components/ClickToCopy.tsx
> +      console.log("onCopy is a thing");
and this

2020-11-10 22:27 UTC, TattdCodeMonkey submitted a review, later dismissed

2020-11-17 15:19 UTC, TattdCodeMonkey approved these changes

2020-11-17 19:42 UTC, TattdCodeMonkey submitted a review, later dismissed

2020-11-17 20:59 UTC, TattdCodeMonkey approved these changes

2020-11-17 21:00 UTC, natmegs approved these changes

2020-11-17 21:00 UTC, merged