Create deploy.yml
dcos-labs/ui-kit pull request #659
Opened 2021-12-10 19:38 UTC by nataliepina

## Testing

## Trade-offs

## Dependencies

## Screenshots

## Checklist for PR creator

- [ ] If any new components were added, there are exported from `packages/index.ts`
- [ ] If this PR is associated with a JIRA, it is mentioned in commit message footer ("Closes …")
- [ ] If this PR contains breaking changes, is stated in commit message body ("BREAKING CHANGE: …")
- [ ] Info for applicable sections above is provided

2021-12-10 20:23 UTC, clintonmedbery submitted a review, later dismissed
This is hard to test because it only runs on a push to master. Maybe we can merge it and see what happens 🤷

2021-12-10 20:25 UTC, clintonmedbery commented
Let's not merge on Friday afternoon in case the deployment does go wrong 😅

2021-12-13 11:20 UTC, mstruebing requested changes
I think we need to use the `setup-node` action as we are executing node/npm commands similar to her: https://github.com/dcos-labs/ui-kit/blob/master/.github/workflows/ci.yml#L23-L27

2021-12-13 14:23 UTC, clintonmedbery approved these changes

2021-12-14 13:12 UTC, mstruebing commented on .github/workflows/ci.yml
>          run: npm install
We do not want to run `install` and `ci` here, what we want is probably only a `npm ci`.
https://docs.npmjs.com/cli/v8/commands/npm-ci

2021-12-14 16:33 UTC, vacas5 reviewed
I think we can split out actions so they can run concurrently. Should we consider pulling this one out? Not sure if there is a way to make them dependent of each other

2021-12-15 21:40 UTC, vacas5 approved these changes

2021-12-17 09:11 UTC, mstruebing approved these changes
👍

2021-12-17 12:50 UTC, merged