phase out jenkins
dcos-labs/ui-kit pull request #663
Opened 2021-12-13 17:19 UTC by nataliepina

We have successfully transferred the actions happening in Jenkins to Github Actions. We will remove the jenkinsfile once all of the actions are confirmed and merged in. 

## Testing

If you'd like, you can compare the jenkinsfile to the ci.yml and integration.yml files. 

## Trade-offs

## Dependencies

## Screenshots

## Checklist for PR creator

- [ ] If any new components were added, there are exported from `packages/index.ts`
- [ ] If this PR is associated with a JIRA, it is mentioned in commit message footer ("Closes …")
- [ ] If this PR contains breaking changes, is stated in commit message body ("BREAKING CHANGE: …")
- [ ] Info for applicable sections above is provided

2021-12-14 13:12 UTC, mstruebing approved these changes
🥳

2021-12-17 16:06 UTC, mstruebing commented
Can we merge this now that #659 is in?

2021-12-21 17:15 UTC, TattdCodeMonkey requested changes
make this a `fix` commit so we can trigger a release.

2021-12-21 17:18 UTC, clintonmedbery approved these changes

2021-12-21 17:21 UTC, TattdCodeMonkey approved these changes

2021-12-21 17:23 UTC, merged