fix: deprecate use of downshift
dcos-labs/ui-kit pull request #717
Opened 2022-05-16 20:40 UTC by vacas5

In an attempted upgrade of downshift I noticed a bug in their types.
Looking into a possible contribution, I then noticed that they have not
merged a PR in about a year. I am not sure if the project is currently
maintained, as all PRs were failing CI.

Instead I am attempting to remove downshift as a dependency altogether,
which should give users more granular control of accessibility concerns.

BREAKING CHANGE:
I will no longer return all of the Downshift props from the onSelect
callback in DropdownMenu.

## Testing

## Trade-offs

## Dependencies

## Screenshots

## Checklist for PR creator

- [ ] If any new components were added, there are exported from `packages/index.ts`
- [ ] If this PR is associated with a JIRA, it is mentioned in commit message footer ("Closes …")
- [ ] If this PR contains breaking changes, is stated in commit message body ("BREAKING CHANGE: …")
- [ ] Info for applicable sections above is provided

2022-05-17 13:59 UTC, nataliepina requested changes
<img width="723" alt="Screen Shot 2022-05-17 at 8 39 35 AM" src="https://user-images.githubusercontent.com/34781875/168828113-cd8c6a04-5a48-49fa-b64a-c45a83336f25.png">
Comparing the changes and it looks like there are some missing flex props that should be passed down to a `div` that is a child of `PopoverListItem` in the `DropdownMenu`. These look to have come from along with Downshift. 

Missing flex props can be seen here:
![Screen Shot 2022-05-17 at 8 58 11 AM](https://user-images.githubusercontent.com/34781875/168828669-9e736872-674b-4d1e-a20b-22ef911eaaba.png)

2022-05-18 11:47 UTC, seialkali commented on tsconfig.json
> -    "lib": ["es6", "dom", "es2017"]
Nice. Just out of curiosity, did adding this fix any issues we were having with TS?

2022-05-20 20:18 UTC, nataliepina commented on packages/popover/components/PopoverListItemIcon.tsx
> +const PopoverListItemIcon = (props: PopoverListItemProps) => (
👏

2022-05-20 20:38 UTC, vacas5 commented
I will more than likely close this, but I'll try and grab some of the nicer parts into another PR

2022-05-22 14:05 UTC, vacas5 commented
For now, I've gotten the upgrade to work. We can possibly revisit this if we find that downshift is indeed abandoned

2022-05-22 14:05 UTC, closed without merging