refactor: convert FormFieldWrapper to FC
dcos-labs/ui-kit pull request #791
Opened 2022-10-06 14:02 UTC by davidtaing

# Description

Refactors FormFieldWrapper to a functional component.

fixes #787

## Which issue(s) does this PR relate to?

- #787 

## Testing

No changes to the UI

## Trade-offs

N/A

## Screenshots

N/A - No Changes to the UI

## Checklist

- [X] If any new components were added, there are exported from `packages/index.ts`
- [ ] This PR is associated with a JIRA and mentions in the commit message footer ("Closes …")
- [ ] This PR contains breaking changes and states in the commit message body ("BREAKING CHANGE: …")
- [X] I have reviewed the changes and provided detail to the sections above

2022-10-06 14:56 UTC, nataliepina commented on packages/shared/components/FormFieldWrapper.tsx
> +};
We've been using React.memo() for components that were previously a `PureComponent`. 

Could you wrap this export below with React.memo()?

`export default React.memo(FormFieldWrapper); ` 

You may need to update the snapshot tests afterward - `npm run test -- -u`

2022-10-06 18:19 UTC, nataliepina requested changes
Was able to test out these changes and the Form related components are functioning as expected. I left one comment requesting a change otherwise.

2022-10-06 19:25 UTC, vacas5 reviewed
agree with @nataliepina here, just need to memoize this one to recreate PureComponent behavior

2022-10-07 00:56 UTC, davidtaing commented
Just made the changes. We should be good to go.

I'm self-taught and I'm finding it difficult to the first development job. So I wanted to sincerly thank you @nataliepina & @vacas5. Thank you for giving me this opportunity. Thank you for making it easy for me to get the project up and running. And thank you for your prompt replies, prompt review and making this a great experience overall.

Please let me know if I can help out anywhere else like any other issues or even other projects that need love.

❤️

2022-10-07 08:50 UTC, mstruebing approved these changes
Thank you @davidtaing these changes look very good from my point of view 🚀

2022-10-07 13:42 UTC, nataliepina commented
@davidtaing Great work! Some of these component refactors can be challenging. I will be adding a few more component refactors to the issues later today. After those, I will be adding some different types of issues. Feel free to add an issue if you come across anything. We appreciate your contributions and I'm happy to hear it was easy for you to get up and running with the project.

2022-10-07 13:42 UTC, nataliepina approved these changes
👏🏻

2022-10-07 13:45 UTC, merged