Refactor TextInput related components from classes to functional components
dcos-labs/ui-kit pull request #801
Opened 2022-10-09 11:07 UTC by alberturria

# Description

This PR changes the following components from being class based ones, to be functional ones:
 - `TextInput`
 - `TextInputWithIcon`
 - `TextInputWithBadges`
 - `TextInputWithButton`
 
 As a side effect of changing the paradigm (ineritance within components), we've created a new file called `utils.ts`, where some shared logic among these components is placed.
 
## Which issue(s) does this PR relate to?
closes #800 

## Testing

A single regression test of the 4 elements mentioned above should be enough for it.

## Trade-offs

There are still some duplicated code between components, such as the following functions:
`getInputAppearance`, we might need to refactor these as well, but since these depends on a state (`hasFocus`) didn't feel in the mood to refactor them.

## Screenshots

Same as before 🙂 

## Checklist

- [x] If any new components were added, there are exported from `packages/index.ts`
- [ ] This PR is associated with a JIRA and mentions in the commit message footer ("Closes …")
- [ ] This PR contains breaking changes and states in the commit message body ("BREAKING CHANGE: …")
- [x] I have reviewed the changes and provided detail to the sections above

2022-10-10 11:13 UTC, seialkali reviewed
Thanks very much for your contribution, and great idea with the utils file for the shared functions! However, I've noticed that we're getting the following console warning when using the `TextInputWithButtons (with custom icons)` component in Storybook:

```
Warning: React does not recognize the `iconStart` prop on a DOM element. 
If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `iconstart` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at input
    at div
    at FormFieldWrapper (webpack:///./packages/shared/components/FormFieldWrapper.tsx?:25:23)
    at div
    at TextInputWithButtons (webpack:///./packages/textInput/components/TextInputWithButtons.tsx?:107:72)
```

I'm not entirely sure why this is happening at the moment, but I think it might have to do with one of the shared functions getting slightly different props from the components using it. Let me know if you would like some help trying to identify the issue, and I can do some digging.

2022-10-10 14:39 UTC, nataliepina commented
Amazing work refactoring this! I like the shared utils file. It's nearly there. 

I've been testing out the stories and I also noticed some issues with the `TextInputWithButtons`.  It's quite slow to switch themes for me. The close button has the error red error theming throughout the success and standard appearances. 
<img width="677" alt="Screen Shot 2022-10-10 at 9 28 19 AM" src="https://user-images.githubusercontent.com/34781875/194890520-3f95a4ac-b0ca-4704-8a65-6922666c77ed.png">
<img width="648" alt="Screen Shot 2022-10-10 at 9 32 28 AM" src="https://user-images.githubusercontent.com/34781875/194890522-fe48bb2a-83cf-40df-be52-9efe6df5b561.png">

2022-10-13 15:15 UTC, nataliepina requested changes
Following up on some requested changes. Are you still working on those? Please let us know if you need any help. Cheers!

2022-10-13 17:49 UTC, alberturria commented
> Following up on some requested changes. Are you still working on those? Please let us know if you need any help. Cheers! 

Hey @nataliepina yep, I plan to tackle the changes during the upcoming weekend. Sorry, but I'm a bit busy with the job during the laboral days 🙏

2022-10-13 17:53 UTC, nataliepina commented
> > Following up on some requested changes. Are you still working on those? Please let us know if you need any help. Cheers!
> 
> Hey @nataliepina yep, I plan to tackle the changes during the upcoming weekend. Sorry, but I'm a bit busy with the job during the laboral days 🙏

No problem, totally understandable. Take the time you need. We really appreciate all of the work you've done here!

2022-10-16 09:51 UTC, alberturria commented
> Thanks very much for your contribution, and great idea with the utils file for the shared functions! However, I've noticed that we're getting the following console warning when using the `TextInputWithButtons (with custom icons)` component in Storybook:
> 
> ```
> Warning: React does not recognize the `iconStart` prop on a DOM element. 
> If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `iconstart` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
>     at input
>     at div
>     at FormFieldWrapper (webpack:///./packages/shared/components/FormFieldWrapper.tsx?:25:23)
>     at div
>     at TextInputWithButtons (webpack:///./packages/textInput/components/TextInputWithButtons.tsx?:107:72)
> ```
> 
> I'm not entirely sure why this is happening at the moment, but I think it might have to do with one of the shared functions getting slightly different props from the components using it. Let me know if you would like some help trying to identify the issue, and I can do some digging.

@seialkali Sharp eye! you are completely right. Checked locally, and 
e247ae0 fixed this issue 🙂 



> Amazing work refactoring this! I like the shared utils file. It's nearly there.
> 
> I've been testing out the stories and I also noticed some issues with the `TextInputWithButtons`. It's quite slow to switch themes for me. The close button has the error red error theming throughout the success and standard appearances. <img alt="Screen Shot 2022-10-10 at 9 28 19 AM" width="677" src="https://user-images.githubusercontent.com/34781875/194890520-3f95a4ac-b0ca-4704-8a65-6922666c77ed.png"> <img alt="Screen Shot 2022-10-10 at 9 32 28 AM" width="648" src="https://user-images.githubusercontent.com/34781875/194890522-fe48bb2a-83cf-40df-be52-9efe6df5b561.png">

@nataliepina I've been diggin into this a couple of days, and after some time, this is what I've seen 👁️ 
- Storybook freezes also on my end as soon as the `TextInputWithButtons` element changes their props.
- The success state keeps showing the red cross. -> This last one I'm pretty sure that it is the expected behaviour, (we're setting the 'red' icon color in the storyBook component). Besides that, the behaviour on the `main` branch is the same 🙂 
![code](https://user-images.githubusercontent.com/32776999/196028667-8b7642b2-4705-46d6-8731-47b02b92962b.png)

Regarding the performance issue, I've realized that I get exactly the same problem in the `main` branch, so I suspect that this it not related to this refactor. Can you check if this also happens to you on `main`?


I'm not an expert at all on performance optimizing, but I think I've spotted the root of the problem. 
The rendering of the memoized `FormFieldWrapper` seems to be the biggest issue here.

![profiler](https://user-images.githubusercontent.com/32776999/196029012-d4ee50cd-f7bc-46bc-82cd-29c7bc169724.png)

2022-10-18 15:11 UTC, nataliepina commented
Can confirm, I have noticed the behavior on `main` too.
Although, I did not encounter it when comparing it to our current production build - https://dcos-labs.github.io/ui-kit/?path=/story/forms-textinputwithbuttons--default

I also tried to revert the changes that refactored ToggleWrapper to a FC from [this PR](https://github.com/dcos-labs/ui-kit/pull/804), on your branch, and I found the behavior to be the same. It also had slow behavior when I removed the memoization from ToggleWrapper.

Any thoughts from anyone else in @dcos-labs/frontend?

2022-10-19 13:13 UTC, seialkali approved these changes
I've tried to work out what's causing storybook to freeze on the `TextInputWithButtons` story and I really can't see any reason for it. I think we should merge this and see if we still get the same issue in production. From what I can tell, it only seems to be an issue locally, and appears more to do with some Storybook weirdness than anything to do with the component itself.

Thanks @alberturria for your work on this, and for fixing that console warning!

2022-10-19 13:35 UTC, nataliepina commented
Thanks for double-checking @seialkali. I wanted to make sure it was the same for someone else locally at least.

2022-10-19 13:35 UTC, nataliepina approved these changes
Thank you for the hard work and bonus refactoring.

2022-10-19 14:47 UTC, merged