refactor: togglecontent component, story, and test
dcos-labs/ui-kit pull request #826
Opened 2022-10-18 18:53 UTC by nataliepina

Refactoring away from enzyme for testing to RTL. 
Updating ToggleContent component to a function component. Simplifying toggle functionality. 
Improving Storybook story for ToggleContent with improved content controls, and better documentation for properties. 

# Description

## Which issue(s) does this PR relate to?

## Testing

## Trade-offs

## Screenshots

## Checklist

- [ ] If any new components were added, there are exported from `packages/index.ts`
- [ ] This PR is associated with a JIRA and mentions in the commit message footer ("Closes …")
- [ ] This PR contains breaking changes and states in the commit message body ("BREAKING CHANGE: …")
- [ ] I have reviewed the changes and provided detail to the sections above

2022-10-18 22:13 UTC, vacas5 requested changes
just need to delete some dupe files

2022-10-18 22:13 UTC, vacas5 commented on packages/toggleContent/components/toggleContent.tsx
> +export default React.memo(ToggleContent);
I think you want to delete this file, because it's duplicated above. Thanks for the easy diff tho

2022-10-18 22:13 UTC, vacas5 commented on packages/toggleContent/stories/ToggleContent.stories.tsx
> +  // }
I'd just ditch this altogether

2022-10-18 22:13 UTC, vacas5 commented on packages/toggleContent/stories/toggleContent.stories.tsx
> +  contentOff: <ToggleComponent componentName="Secondary Component" />
did you mean to delete this file?

2022-10-18 22:17 UTC, nataliepina commented on packages/toggleContent/components/toggleContent.tsx
> +export default React.memo(ToggleContent);
oops! yep

2022-10-18 22:20 UTC, nataliepina commented on packages/toggleContent/components/toggleContent.tsx
> +export default React.memo(ToggleContent);
I think there is some weirdness going on because I renamed the files, it should have deleted the lowercase with that. Will figure it out and fix.

2022-10-18 22:26 UTC, vacas5 commented on packages/toggleContent/components/toggleContent.tsx
> +export default React.memo(ToggleContent);
you probably just forgot to commit them too

2022-10-18 22:36 UTC, nataliepina commented on packages/toggleContent/components/toggleContent.tsx
> +export default React.memo(ToggleContent);
It's something with trying to commit file renames that change casing in this repo. We saw something similar in trying to change `badgeButton` still trying to figure it out. I attempted using `git config core.ignorecase false` and it may be the culprit of the issues.

2022-10-18 22:38 UTC, nataliepina commented on packages/toggleContent/components/toggleContent.tsx
> +export default React.memo(ToggleContent);
When I go into the project I will see the files renamed and I do not see a duplicate also. I'm going to revert to the lowercase names for now and will try to dig more into the root cause.

2022-10-19 11:21 UTC, mstruebing commented on packages/toggleContent/components/toggleContent.tsx
> +export default React.memo(ToggleContent);
I remember there were issues with case-insensitive file systems on Mac years ago, not sure if this is still a thing, but maybe that helps for googling.

2022-10-19 11:35 UTC, seialkali approved these changes
👌

2022-10-19 13:39 UTC, nataliepina commented on packages/toggleContent/components/toggleContent.tsx
> +export default React.memo(ToggleContent);
Interesting! That could definitely be it. I am going to see if I can fix this. I followed the top comment on this [Stack overflow thread](https://stackoverflow.com/questions/6899582/i-change-the-capitalization-of-a-directory-and-git-doesnt-seem-to-pick-up-on-it) looks like someone else had an issue with duplicated files as well.

2022-10-19 16:56 UTC, vacas5 approved these changes

2022-10-19 17:03 UTC, merged